### PR TITLE
Delay server closing process until all save jobs are completed

### PR DESCRIPTION
**Pull request by FireBird702**

### CODE REVIEW

**Comment by noahrepublic** [comment]
This all looks good, I tested it, and it seems to work. But, the ```:await``` on checking the datastore is live (mock detection) is causing some weird behaviours. 

I think if the ```:await``` hasn't yet been resolved at the time of ```.GetStore``` the promise GetStore returns should await for the mock detection.

**Comment by FireBird702** [comment]
Maybe you could look at it because I have no idea how it should be done

**Review by noahrepublic — APPROVED** [review]
This looks good. 

One thing with awaiting in GetStore is it takes too long that some players will join before the Player.PlayerAdded is connected (in the example on docs, and in most cases.) Should this be mentioned as a breaking change?

**Comment by FireBird702** [comment]
I think so.

**Pull request merged**
